### ISSUE TITLE
Add quick5_fluency?

### ISSUE THREAD

**Issue by eight04** [rime/rime-quick#2]
最近Windows 10又把新倉頡弄壞，尋找替代品時發現了RIME，體驗了它的拼音後感覺很有潛力。

遇到最大的困難是找不到文件，wiki的教學非常長但沒有參考。

目前成果如下︰
```yaml
# Rime schema settings
# encoding: utf-8

__include: quick5.schema.yaml:/

__patch:
  "switches/@0/reset": 1  #表示將 switcher 列表中的第一個元素（即 ascii_mode 開關）的初始值重設爲狀態1（即「英文」）。

schema:
  schema_id: quick5_fluency
  name: 新倉頡
  version: "0.20"
  dependencies:
    - luna_quanpin

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - fluency_editor
  segmentors:
    - ascii_segmentor
    - matcher
    # 不使用內建的abc_segmentor
    # - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - script_translator
    - reverse_lookup_translator
  filters:
    - simplifier
    - uniquifier
    - single_char_filter

speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba
  delimiter: " ;'"
  algebra: 
    # 不使用速成碼
    # - 'derive/^([^z])\w+(\w)$/$1$2/'  # 取倉頡首尾二碼爲速成碼
    # 要求單碼必須接空格
    - 'xform/^(\w)$/$1 /' 


punctuator:
  # 把空格視為符號
  use_space: true
  half_shape:
    __include: punctuation.yaml:ascii_style
    # 使用commit時，會把緩充區上屏，再打出空格
    ' ' : { commit: ' ' }
    # 不使用cmomit，會把空格輸入援充區
    # ' ' : ' '
    # TODO: 把所有符號都改成 commit
    # FIXME: 合併錯誤？
    # '#' : { commit: '#' }
    # "'" : { commit: "'" }
    # '"' : { commit: '"' }

recognizer:
  import_preset: default
  patterns:
    reverse_lookup: "`[a-z]*'?$"
    # 字母|字母後接單空格
    abc: "[a-z]+( [a-z]+)* ?"
      

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: commit_text # 左Shift切換英數
    Shift_R: commit_code # 右Shift切換英數，並把緩充區以英文字母上屏
    Control_L: noop
    Control_R: noop
    Caps_Lock: noop
    Eisu_toggle: clear
```

與微軟新倉頡有些差異︰

1. 字典有些不一樣，如「麵」
2. 可以使用空格隔字，非必需
3. 空白鍵會將緩充區上屏後才打出空白。微軟新倉頡是在緩充區沒有內容時直接上屏，否則把空白輸入緩充區
4. 其它的半型符號同3
5. 緩充區有內容時，打出大寫字母後，後續的小寫字母會變成英文。把大寫英文加入punctuator/half_shape也無法解決
